name: SpawnerTools
version: 0.3
api-version: 1.13
main: de.laparudi.spawnertools.SpawnerTools
author: LapaRudi
description: Vereinfach den Umgang mit Spawnern
softdepend:
  - PlotSquared
  - Essentials
commands: 
  spawnertools:
    aliases: [st, stools]